### ISSUE TITLE
Mahmoud : separation-of-concerns

### ISSUE THREAD

**Issue by krakla** [HackYourFutureBelgium/class-11-12#226]
> [module repository](https://github.com/HackYourFutureBelgium/separation-of-concerns)

## Suggested Study

- [x] Separation of Concerns
- [x] Code in this Repo
- [x] JavaScript 30
- [ ] Repos of practice
- [x] Generating HTML with Template Literals
- [x] The DOM
- [ ] Events
- [ ] Learn Form Validation
- [x] Fun projects on YouTube

---

## Week 1

- [x] Sunday Prep

- [x] Sunday Class

### Project

[javascript-30-gallery](https://github.com/AnisyaPurnama/javascript-30-gallery)

 The JavaScript 30 put together by Wes Bos. This week:
- [x] #1: JavaScript Drum Kit
- [x] #3: CSS Variables
- [x] #5: Flex Panel Gallery
- [x] #8: Fun with HTML5 Canvas
- [x] #10: Hold Shift and Check Checkboxes
- [x] #13: Slide in on Scroll
- [x] #16: Mouse Move Shadow
- [ ] #18: Adding Up Times
- [ ] #20: Speech Recognition
- [ ] #22: Follow Along Link Highlighter
- [ ] #25: Event Capture, Propagation, Bubbling and Once
- [ ] #28: Video Speed Controller

### Check-In

__Progress__
- A lot of reading, the javascript.info is a nice website.
- Code in this Repo: isolate, 02-add-event-listener
- JavaScript 30: JavaScript Drum Kit

__Blocked__

__Next Steps__
Continue practicing with the JS30.

__Tip(s) of the week__
💻 🍗🍗🍗
