### ISSUE TITLE
Your Name: Module Name

### ISSUE THREAD

**Issue by 22count22** [HackYourFutureBelgium/class-11-12#230]
> [module repository](https://github.com/HackYourFutureBelgium/separation-of-concerns)

## Suggested Study

- [x] Separation of Concerns
- [x] Code in this Repo
- [x] JavaScript 30
- [x] Repos of practice
- [x] The DOM
- [ ] Fun projects on YouTube

---

## Week 1

- [x] Sunday Prep

- [x] Sunday Class

### Project

[javascript-30-gallery](https://github.com/AnisyaPurnama/javascript-30-gallery)

 The JavaScript 30 put together by Wes Bos. This week:
- [x] #1: JavaScript Drum Kit
- [x] #3: CSS Variables
- [x] #5: Flex Panel Gallery
- [ ] #8: Fun with HTML5 Canvas
- [ ] #10: Hold Shift and Check Checkboxes
- [ ] #13: Slide in on Scroll
- [ ] #16: Mouse Move Shadow
- [ ] #18: Adding Up Times
- [ ] #20: Speech Recognition
- [ ] #22: Follow Along Link Highlighter
- [ ] #25: Event Capture, Propagation, Bubbling and Once
- [ ] #28: Video Speed Controller

### Check-In

__Progress__
 I'm practicing a lot from the new material and the old one.

__Blocked__
I was blocked, on my feeeling 😄 

__Next Steps__
- I'm preparing for the coming week.
- waiting for the weekend to come.

__Tip(s) of the week__
wait for next week, this week I don't have tips, not even a one 😄 I was sick.

**Comment by colevandersWands** [comment]
> I was blocked, on my feeeling 😄

You were so joyful you couldn't code?!  nice : )

**Comment by colevandersWands** [comment]
@22count22, do you have any specific question about `import`/`export`?  We can spend some time reviewing it on in class on Sunday if you come with your questions

**Comment by 22count22** [comment]
> @22count22, do you have any specific question about `import`/`export`? We can spend some time reviewing it in class on Sunday if you come with your questions

yes! I have some questions about export and import. that will be appreciated on coming Sunday.
