### ISSUE TITLE
Group 3 : Asynchronous-programming, week 3

### ISSUE THREAD

**Issue by samirm00** [HackYourFutureBelgium/class-11-12#301]
# Project Name

- _Group 3_
- _project leader_ : _project leader_ 
- _repository owner_ : _samirm00_

#### Todo list

- [ ] [repo](https://github.com/_/_) (with a complete README)
- Planning
  - [ ] [Backlog](https://github.com/_/_/tree/master/project-planning/backlog.md)
  - [ ] [Development Strategy](https://github.com/_/_/tree/master/project-planning/development-strategy.md)
  - [ ] [Project board](https://github.com/_/_/projects/_)
- Implementation
  - [ ] ES Modules (`import`/`export`)
  - [ ] at least one `class`
  - [ ] `async`/`await`
  - [ ] Logs of each user interaction
- [ ] [deployed demo]() (optional challenge)

**Comment by bramdevries** [comment]
I was slightly confused that when adding a new todo the previous one would be removed. There's room for improvement on the UX-front to make it feel more like an application but seeing as the focus is on the interaction with the API, I'd say you did a good job.

It feels strange that in order to [get a list of todos](https://github.com/samirm00/todo-lists-restful-pjs/blob/master/public/src/handlers/handleGetAllTodos.js) you first have to do `new Todo`. In cases like this it's a good idea to introduce collection objects that work on a collection of instances, such as a `TodoList` object that takes `Todo` instances. This would allow you to do something like:

```js
async function getTodos() {
	const response = await fetch('/todos');
	const todos = await response.json();

	return new Todolist(data.map(todo => new Todo(todo)));
}
```

This `Todolist` class could have it's own render method that renders a list of todos, or it has methods such as `todolist.add(todo)`, which would handle the creation of a new todo via the API.

**Comment by samirm00** [comment]
@bramdevries I will dived the class to a different class ! 
BUT , you don't have to add todo , to get a list of todos 
![1](https://user-images.githubusercontent.com/67711948/108637205-fb46e100-7489-11eb-9a76-82a3ff917a44.png)
- you can add todo , get all todos(list of todos) , or get one todo by id .

- when you add a new todo the pervous one is not deleting , it is showing the whole list of todos.
Thank you so much for your advice

**Comment by samirm00** [comment]
Thank you @bramdevries  I will divide the class to more reusable classes.
